version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npx serve -s build -l 3000
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - REACT_APP_API_URL=http://backend:8000
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: lospollos
      MONGO_INITDB_ROOT_PASSWORD: andreslikesweiner
